from django.conf import settings

FEATURE_SETTING = getattr(settings, 'FEATURE_FLIPPER', {})

_DEFAULT_FEATURE_FLAGS = ()

FEATURE_FLAGS = FEATURE_SETTING.get('FEATURE_FLAGS', _DEFAULT_FEATURE_FLAGS)
AUTH_USER_MODEL = settings.AUTH_USER_MODEL
